private
setupButtons
	clearTurtleButton
		label: 'ClearT';
		icon: (ScratchTheme formAt: #clearTurtlesButtonGray);
		help: 'Clear turtles'.
	clearPatchesButton
		label: 'ClearP';
		icon: (ScratchTheme formAt: #clearGraphicsButtonGray);
		help: 'Clear patches'.
	setupButton
		label: 'Setup';
		icon: (ScratchTheme formAt: #setupButtonGray);
		help: 'Setup'.
	stopButton
		label: 'Stop';
		icon: (ScratchTheme formAt: #stopButtonGray);
		help: 'Stop'.
	stepButton
		label: 'Step';
		icon: (ScratchTheme formAt: #stepButtonGray);
		help: 'Step'.
	eventButton
		label: 'Event';
		icon: (ScratchTheme formAt: #eventButtonGray);
		help: 'Event'.
	loopSlowButton
		label: 'Slowly';
		icon: (ScratchTheme formAt: #loopSlowButtonGray);
		help: 'Loop slowly'.
	loopButton
		label: 'Loop';
		icon: (ScratchTheme formAt: #loopButtonGray);
		help: 'Loop'