private
setupFont: aTheme
	aTheme fontAt: #Arg name: 'Verdana' size: 10.
	aTheme fontAt: #Label name: 'VerdanaBoldNarrowSpace' size: 10.
	aTheme fontAt: #MenuTitle name: 'VerdanaBold' size: 14.
	aTheme fontAt: #Button name: 'VerdanaBold' size: 10.
	aTheme fontAt: #Category name: 'VerdanaBold' size: 10.
	aTheme fontAt: #Tab name: 'VerdanaBold' size: 11.
	aTheme fontAt: #CommentBlock name: 'Verdana' size: 10.
	aTheme fontAt: #TalkBubble name: 'VerdanaBold' size: 12.
	aTheme fontAt: #ToolTip name: 'Verdana' size: 13.
	aTheme fontAt: #ReporterToolTip name: 'Verdana' size: 14.
	aTheme fontAt: #XYReadout name: 'Verdana' size: 10.
	aTheme fontAt: #XYReadoutBold name: 'VerdanaBold' size: 10.
	aTheme fontAt: #CostumesPage name: 'VerdanaBold' size: 11.
	aTheme fontAt: #SoundsPage name: 'VerdanaBold' size: 11.
	aTheme fontAt: #ViewerPage name: 'VerdanaBold' size: 11.
	aTheme fontAt: #UpdatingStringField name: 'VerdanaBold' size: 11.
	aTheme fontAt: #Watcher name: 'VerdanaBold' size: 10.
	aTheme fontAt: #WatcherLarge name: 'VerdanaBold' size: 14.
	aTheme fontAt: #PaintUtilityButton name: 'VerdanaBold' size: 10.
	aTheme fontAt: #PaintSetRotationCenter name: 'VerdanaBold' size: 11.
	aTheme fontAt: #LibraryItemName name: 'VerdanaBold' size: 9	.
	aTheme fontAt: #LibraryItemInfo name: 'Verdana' size: 6	.
	aTheme fontAt: #MediaItemInfo name: 'Verdana' size: 9	.
	aTheme fontAt: #DialogBoxTitle name: 'VerdanaBold' size: 14.
	aTheme fontAt: #DialogBoxMessage name: 'VerdanaBold' size: 13.
	aTheme fontAt: #DialogBoxButton name: 'VerdanaBold' size: 11.
	aTheme fontAt: #ProjectNotes name: 'Verdana' size: 10.
	aTheme fontAt: #LinkMorphDefault name: 'VerdanaBold' size: 10.
	aTheme fontAt: #ShareLink name: 'VerdanaBold' size: 13.
	aTheme fontAt: #SoundRecorderButton name: 'VerdanaBold' size: 13.
	aTheme fontAt: #SoundRecorderTimer name: 'NewYorkBold' size: 10.
	aTheme fontAt: #StringDialogTypeIn name: 'Verdana' size: 12.
	aTheme fontAt: #NewVariableDialogBox name: 'Verdana' size: 11.
	aTheme fontAt: #AboutScratch name: 'VerdanaBold' size: 11.
	aTheme fontAt: #UploadTagLabel name: 'VerdanaBold' size: 10.
	aTheme fontAt: #UploadTag name: 'Verdana' size: 10.
	aTheme fontAt: #UploadDialogLabel name: 'VerdanaBold' size: 10.
	aTheme fontAt: #UploadDialogContents name: 'Verdana' size: 10.
	aTheme fontAt: #UploadDialogComment name: 'Verdana' size: 10.
	aTheme fontAt: #FolderShortcut name: 'Verdana' size: 11.
	aTheme fontAt: #FileChooserNewFileTitle name: 'VerdanaBold' size: 10.
	aTheme fontAt: #FileChooserNewFilename name: 'Verdana' size: 10.
	aTheme fontAt: #FileChooserLabel name: 'VerdanaBold' size: 10.
	aTheme fontAt: #FileChooserContents name: 'Verdana' size: 12.
	aTheme fontAt: #FileChooserComment name: 'Verdana' size: 10.
	aTheme fontAt: #FilePickerDirectoryName name: 'VerdanaBold' size: 9	.
	aTheme fontAt: #FilePickerEntry name: 'Verdana' size: 11.
	aTheme fontAt: #FilePickerEntryHighlighted name: 'VerdanaBold' size: 11.
	aTheme fontAt: #FrameMorphProjectTitle name: 'VerdanaBold' size: 13