enum SteloSymbol {
  SS_nop = -1,
  SS_push0, /* 0 */
  SS_push1, /* 1 */
  SS_pushShort, /* 2 */
  SS_pushFloat, /* 3 */
  SS_abs, /* 4 */
  SS_acos, /* 5 */
  SS_aimHigh, /* 6 */
  SS_and, /* 7 */
  SS_appendToList, /* 8 */
  SS_asin, /* 9 */
  SS_atan, /* 10 */
  SS_broadcast, /* 11 */
  SS_call, /* 12 */
  SS_changeBreedVarBy, /* 13 */
  SS_clearBreed, /* 14 */
  SS_clearList, /* 15 */
  SS_clearPlots, /* 16 */
  SS_clearTurtles, /* 17 */
  SS_copyBreedVarTo, /* 18 */
  SS_cos, /* 19 */
  SS_createPatch, /* 20 */
  SS_createTurtles, /* 21 */
  SS_dec, /* 22 */
  SS_deleteLineOfList, /* 23 */
  SS_diffuse, /* 24 */
  SS_diffuse4, /* 25 */
  SS_direction, /* 26 */
  SS_div, /* 27 */
  SS_drop, /* 28 */
  SS_dup, /* 29 */
  SS_dx, /* 30 */
  SS_dy, /* 31 */
  SS_equal, /* 32 */
  SS_exp, /* 33 */
  SS_exp10, /* 34 */
  SS_forward, /* 35 */
  SS_getBreedId, /* 36 */
  SS_getBreedVar, /* 37 */
  SS_getId, /* 38 */
  SS_getLineOfList, /* 39 */
  SS_getVar, /* 40 */
  SS_getX, /* 41 */
  SS_getY, /* 42 */
  SS_hatch, /* 43 */
  SS_inv, /* 44 */
  SS_jump, /* 45 */
  SS_jumpIfFalse, /* 46 */
  SS_jumpIfTrue, /* 47 */
  SS_kill, /* 48 */
  SS_less, /* 49 */
  SS_lessEqual, /* 50 */
  SS_lineCountOfList, /* 51 */
  SS_listContains, /* 52 */
  SS_ln, /* 53 */
  SS_log, /* 54 */
  SS_minus, /* 55 */
  SS_mod, /* 56 */
  SS_mul, /* 57 */
  SS_multiplyBreedVarBy, /* 58 */
  SS_not, /* 59 */
  SS_nsum, /* 60 */
  SS_nsum4, /* 61 */
  SS_or, /* 62 */
  SS_patchAt, /* 63 */
  SS_plotColor, /* 64 */
  SS_plotData, /* 65 */
  SS_plus, /* 66 */
  SS_randomFromTo, /* 67 */
  SS_return, /* 68 */
  SS_returnValue, /* 69 */
  SS_rot, /* 70 */
  SS_rounded, /* 71 */
  SS_scaleColorFromTo, /* 72 */
  SS_setBreedVarTo, /* 73 */
  SS_setColorTo, /* 74 */
  SS_setHeading, /* 75 */
  SS_setLineOfListTo, /* 76 */
  SS_setPatchColorTo, /* 77 */
  SS_setPlotYMax, /* 78 */
  SS_setPlotYMin, /* 79 */
  SS_setRandomSeed, /* 80 */
  SS_setVarTo, /* 81 */
  SS_setX, /* 82 */
  SS_setY, /* 83 */
  SS_sin, /* 84 */
  SS_sqrt, /* 85 */
  SS_stop, /* 86 */
  SS_stopAll, /* 87 */
  SS_swap, /* 88 */
  SS_tan, /* 89 */
  SS_truncated, /* 90 */
  SS_turtleAt, /* 91 */
  SS_xyOf, /* 92 */
};
