initialization
setupButtons
	buttonBasic := self newButton
		label: 'Basic';
		yourself.
	buttonControl := self newButton
		label: 'Control';
		yourself.
	buttonColor := self newButton
		label: 'Color';
		yourself.
	buttonSensing := self newButton
		label: 'Sensing';
		yourself.
	buttonPatch := self newButton
		label: 'Patch';
		yourself.
	buttonOperators := self newButton
		label: 'Operators';
		yourself.
	buttonPen := self newButton
		label: 'Pen';
		yourself.
	buttonVariables := self newButton
		label: 'Variables';
		yourself